import { Component, Input } from '@angular/core';
import { CommonModule } from '@angular/common';
import { PageLayoutComponent } from '../../components/page-layout/page-layout.component';

/** Shared component for Terms, Privacy, Cookies */
@Component({
  selector: 'app-legal',
  standalone: true,
  imports: [CommonModule, PageLayoutComponent],
  template: `
<app-page-layout [title]="title" [subtitle]="subtitle" eyebrow="Legal">
  <div class="legal-notice">
    ⚠ This is a placeholder document. Have a qualified legal professional review and replace this content before go-live.
  </div>
  <div class="legal-body">
    <div *ngFor="let s of sections" class="legal-section">
      <h2 class="legal-h2">{{ s.heading }}</h2>
      <p *ngFor="let p of s.paras">{{ p }}</p>
    </div>
  </div>
  <p class="legal-date">Last updated: 1 October 2026</p>
</app-page-layout>`,
  styles: [`
    .legal-notice { background: var(--warning-bg); color: var(--warning); padding: 12px 16px; border-radius: var(--radius-sm); font-size: .82rem; margin-bottom: 32px; font-weight: 600; }
    .legal-body { display: flex; flex-direction: column; gap: 32px; }
    .legal-section {}
    .legal-h2 { font-size: 1rem; font-weight: 700; color: var(--navy); margin-bottom: 10px; }
    p { font-size: .9rem; color: var(--text-2); line-height: 1.8; margin-bottom: 8px; }
    .legal-date { font-size: .8rem; color: var(--text-muted); margin-top: 40px; }
  `]
})
export class LegalComponent {
  @Input() title = '';
  @Input() subtitle = '';
  @Input() sections: { heading: string; paras: string[] }[] = [];
}

// ── Terms ────────────────────────────────────────────────────
@Component({
  selector: 'app-terms',
  standalone: true,
  imports: [LegalComponent],
  template: `<app-legal title="Terms of service" subtitle="Please read these terms carefully before using the VAN DIRECT platform." [sections]="sections"></app-legal>`
})
export class TermsComponent {
  sections = [
    { heading: '1. Acceptance of terms', paras: ['By accessing or using the VAN DIRECT platform you agree to be bound by these Terms of Service. If you do not agree, do not use the platform.'] },
    { heading: '2. Service description', paras: ['VAN DIRECT provides an on-demand parcel delivery service that connects customers with independent drivers operating within agreed service areas in Tunisia.'] },
    { heading: '3. User accounts', paras: ['You must provide accurate information when creating an account. You are responsible for maintaining the confidentiality of your credentials and for all activities that occur under your account.'] },
    { heading: '4. Prohibited items', paras: ['You may not ship flammable or explosive materials, illegal substances, live animals, counterfeit goods, or any item prohibited by Tunisian law.'] },
    { heading: '5. Liability', paras: ['VAN DIRECT\'s liability is limited to the declared value of the parcel, subject to the conditions set out in the Damage and Loss Policy. We are not liable for indirect or consequential losses.'] },
    { heading: '6. Changes to terms', paras: ['We reserve the right to update these terms at any time. Continued use of the platform after changes constitutes acceptance of the revised terms.'] },
  ];
}

// ── Privacy ──────────────────────────────────────────────────
@Component({
  selector: 'app-privacy',
  standalone: true,
  imports: [LegalComponent],
  template: `<app-legal title="Privacy policy" subtitle="How VAN DIRECT collects, uses and protects your personal data." [sections]="sections"></app-legal>`
})
export class PrivacyComponent {
  sections = [
    { heading: '1. Data we collect', paras: ['We collect data you provide directly (name, email, phone, addresses) and data generated by your use of the platform (shipment history, GPS location when you are an active driver, device information).'] },
    { heading: '2. How we use your data', paras: ['To process and deliver shipments, to communicate order status, to improve our services, to prevent fraud, and where required by law.'] },
    { heading: '3. Data sharing', paras: ['We share your data only with assigned drivers (name, phone, pickup address) and with service providers under confidentiality agreements. We do not sell personal data.'] },
    { heading: '4. Retention', paras: ['Account data is retained while your account is active and for 5 years thereafter to comply with legal obligations. You may request deletion by contacting support.'] },
    { heading: '5. Your rights', paras: ['Under applicable Tunisian data-protection law you have the right to access, correct and delete your personal data. Contact support to exercise these rights.'] },
    { heading: '6. Cookies', paras: ['See our Cookie Policy for details on how we use cookies and tracking technologies.'] },
  ];
}

// ── Cookies ──────────────────────────────────────────────────
@Component({
  selector: 'app-cookies',
  standalone: true,
  imports: [LegalComponent],
  template: `<app-legal title="Cookie policy" subtitle="Information about the cookies VAN DIRECT uses and how to control them." [sections]="sections"></app-legal>`
})
export class CookiesComponent {
  sections = [
    { heading: 'What are cookies?', paras: ['Cookies are small text files stored on your device when you visit a website. They help the site remember your preferences and improve your experience.'] },
    { heading: 'Cookies we use', paras: ['Session cookies (strictly necessary — expire when you close the browser), preference cookies (remember your language and theme choice), analytics cookies (understand how visitors use the site — disabled until consent is given).'] },
    { heading: 'Third-party cookies', paras: ['We currently do not load any third-party advertising cookies. Analytics are self-hosted.'] },
    { heading: 'Managing cookies', paras: ['You can disable cookies in your browser settings. Note that disabling session cookies will prevent you from logging in.'] },
  ];
}
